# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86416be368f6d95373fd5b84d2df26350050c36a6bfaeb7c189532b6b7a7a82ffdf46035923ac0e85e2aa2a0e26b439c9950014962707ef3f040ab723175a505

test:
  secret_key_base: f60751a814646d4dfc1f743e78583da4df2507f8f7bcfd69ba7b0e1b8b17a94720abe1642e75a5774cae6a79544f1e12a2e55b817bd9b30459ddeb05471f30df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
